/*
 * Ski Data API for NEU Seattle distributed systems course
 * An API for an emulation of skier managment system for RFID tagged lift tickets. Basis for CS6650 Assignments for 2019
 *
 * OpenAPI spec version: 1.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.model.ResponseMsg;
import io.swagger.client.model.TopTen;
import java.util.Arrays;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResortsApi
 */
@Ignore
public class ResortsApiTest {

    private final ResortsApi api = new ResortsApi();

    /**
     * get the top 10 skier vertical totals for this day
     *
     * get the top 10 skier vertical totals for this day
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTopTenVertTest() throws ApiException {

        // TODO: test validations
        String defaultResort = "SilverMt";
        String skiDay = "1";
        // String basePath = "http://34.216.83.150:8080/Servlets_war/skiers/";
        String basePath = "http://localhost:8080/Servlets_war_exploded/";

        ApiClient client = api.getApiClient();
        client.setBasePath(basePath);

        List<String> resort = Arrays.asList(defaultResort); // List<String> | resort to query by
        List<String> dayID = Arrays.asList(skiDay); // List<String> | day number in the season
        try {
            TopTen result = api.getTopTenVert(resort, dayID);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling ResortsApi#getTopTenVert");
            e.printStackTrace();
        }
    }
}
